Add External Engine API methods
ion232/lichess-api pull request #14
Opened 2023-11-16 13:51 UTC by joshka

- style: run cargo fmt
- fix: correct model for puzzle activity
- docs: extend the example code to be a cli for lichess
- feat: add tracing of request and response
- feat: add external engine API methods
- feat: add engine analyse

2023-12-23 00:52 UTC, joshka commented
Rebased on main and cleaned up the commits - I haven't looked at this in a while, so I've forgotten where it was up to. Just pushing what I had locally

2023-12-23 16:58 UTC, ion232 commented
I've just pushed some changes that add support for other domains in a way that's different to yours. The domain is now part of the request itself, but defaults to lichess.org, so it isn't really noticeable unless you need to change it. You'll have to update your code to use that for the `engine.lichess.ovh` endpoints

2023-12-24 00:21 UTC, joshka commented
Neat - thanks for that :)

2024-01-27 15:13 UTC, ion232 requested changes
Hi @joshka

Thanks for your work on the external engine. I'd like to get it into the `main` branch so it's not diverging while other changes are going in. I'll look into finishing it off once its in there. I've suggested a few bits of cleanup before it's ready.

2024-01-27 15:13 UTC, ion232 commented on Cargo.toml
> +# awc = ["dep:actix-web", "dep:awc", "dep:webpki-roots", "dep:mime", "dep:rustls"]
```suggestion
```

2024-01-27 15:13 UTC, ion232 commented on examples/lichess.rs
> +
```suggestion
```

2024-01-27 15:13 UTC, ion232 commented on src/api/external_engine.rs
> +        debug!("Creating external engine: {:?}", request);
```suggestion
```

2024-01-27 15:13 UTC, ion232 commented on src/api/external_engine.rs
> +    pub async fn aquire_analysis_request(
```suggestion
    pub async fn acquire_analysis_request(
```

2024-01-27 15:13 UTC, ion232 commented on examples/lichess.rs
> +                }
```suggestion
                let mut analysis = lichess.acquire_analysis_request(request.clone()).await?;
                while wait && analysis.is_none() {
                    tracing::debug!("No analysis request available");
                    analysis = lichess.acquire_analysis_request(request.clone()).await?;
                }
```

2024-01-28 13:03 UTC, ion232 approved these changes

2024-01-28 13:04 UTC, merged